apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: '{{ .Release.Namespace }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: manifest-template-operator-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: manifest-template-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: manifest-template-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: manifest-template-operator-controller-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: manifest-template-operator-manager-optional-role
{{- with .Values.optionalClusterRoleRules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: manifest-template-operator-manager-optional-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manifest-template-operator-manager-optional-role
subjects:
  - kind: ServiceAccount
    name: manifest-template-operator-controller-manager
    namespace: '{{ .Release.Namespace }}'
