apiVersion: v1
entries:
  manifest-template-operator:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-04-26T18:20:59.997485+09:00"
    description: Deploy manifest-template-controller that generate and apply manifest
      from template
    digest: bfa4816221e00c5951723e76e536cd0e1798658fa07b08324eb99d5d53b74c11
    name: manifest-template-operator
    type: application
    urls:
    - manifest-template-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-04-26T18:20:59.99692+09:00"
    description: Deploy manifest-template-controller that generate and apply manifest
      from template
    digest: eca1c400e6f1ff395ca75454baa594811102faf5ce9de0a47ff63894908e48bf
    name: manifest-template-operator
    type: application
    urls:
    - manifest-template-operator-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2023-04-26T18:20:59.996341+09:00"
    description: Deploy manifest-template-controller that generate and apply manifest
      from template
    digest: a417d04cdcdae6654bbabea1015c4ae2c45159bc0da5575102da51926fd28ba3
    name: manifest-template-operator
    type: application
    urls:
    - manifest-template-operator-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-04-26T18:20:59.995851+09:00"
    description: Deploy manifest-template-controller that generate and apply manifest
      from template
    digest: 46d4bacde67c41e29e41ef1de34817a2e4fad17912c39591f72aabf8db1111bd
    name: manifest-template-operator
    type: application
    urls:
    - manifest-template-operator-0.0.3.tgz
    version: 0.0.3
generated: "2023-04-26T18:20:59.995275+09:00"
