apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-controller-manager
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernets.io/managed-by: kustomize
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-leader-election-role
  namespace: '{{ .Release.Namespace }}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - manifest-template.takumakume.github.io
    resources:
      - manifesttemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - manifest-template.takumakume.github.io
    resources:
      - manifesttemplates/finalizers
    verbs:
      - update
  - apiGroups:
      - manifest-template.takumakume.github.io
    resources:
      - manifesttemplates/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-leader-election-rolebinding
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-template-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: ingress-template-operator-controller-manager
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-template-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: ingress-template-operator-controller-manager
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-template-operator-proxy-role
subjects:
  - kind: ServiceAccount
    name: ingress-template-operator-controller-manager
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: manifest-template-operator
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: manifest-template-controller
    app.kubernetes.io/part-of: manifest-template-operator
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{ include "manifest-template-operator.chart" . }}'
  name: ingress-template-operator-controller-manager-metrics-service
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-template-operator
    control-plane: controller-manager
